#!bin/bash

echo "Checking If Older Version Of Searchit Exist..."
if [ -f /usr/bin/searchit ] || [ -f /usr/bin/googleit ] || [ -f /usr/bin/duckit ] || [ -f /usr/share/applications/st.desktop ] || [ -d ~/.searchit ] || [ -d /usr/share/icons/SearchitTerminal ] || [ -f /usr/share/applications/SearchitTerminal.desktop ] || [ -d /usr/share/SearchitTerminal ]
    then {
            echo "Older Version Of Searchit Terminal Is Found"
            echo "Removing Old Version Files..."
            if [ -f /usr/bin/searchit ]
            then
              sudo rm /usr/bin/searchit /usr/bin/googleit /usr/bin/duckit
            fi

            if [ -f /usr/share/applications/SearchitTerminal.desktop ]
            then
              sudo rm /usr/share/applications/SearchitTerminal.desktop
            fi

            if [ -d /usr/share/SearchitTerminal ]
            then
              sudo rm -r /usr/share/SearchitTerminal
            fi

            if [ -d /usr/share/icons/SearchitTerminal ]
            then
              sudo rm -r /usr/share/icons/SearchitTerminal
            fi

            if [ -d ~/.searchit ]
            then
              sudo rm -r ~/.searchit
            fi

            if [ -f /usr/share/applications/st.desktop ]
            then
              sudo rm /usr/share/applications/st.desktop ]
            fi
            echo "Old Version Of Searchit Terminal Removed"
          }
        else {
          echo " No Older Version Of Searchit Terminal Is Found"
        }
fi
echo "Installing Newer Version Of Searchit Terminal"
