#!bin/bash

normal=`echo -en "\e[0m"`
RED=`echo -en "\e[41m"`
red=`echo -en "\e[31m"`
BLACK=`echo -en "\e[40m"`
bold=`echo -en "\e[1m"`
blink=`echo -en "\e[5m"`
orange=`echo -en "\e[33m"`
# Checking For dependencies

echo "Checking dependencies..."
dep0=$(which wget)
if [ -n "$dep0" ]
then
  echo "All dependencies are availavle "
else {
  clear
  echo "${red}${blink}ERROR: Dependencies are not availavle${normal}"
  echo "${red}Searchit-Terminal dependes on the package \"wget\"${normal}"
  echo "Install \"Wget\" Manually Just Run This Command"
  echo "${BLACK}${orange}\" sudo apt install wget \"${normal}"
  echo "All dependencies are installed"
 }
fi

# Checking for old version

echo "Checking If Older Version Of Searchit Exist..."
if [ -f /usr/bin/searchit ] || [ -f /usr/bin/googleit ] || [ -f /usr/bin/duckit ] || [ -f /usr/share/applications/st.desktop ] || [ -d ~/.searchit ] || [ -d /usr/share/icons/SearchitTerminal ] || [ -f /usr/share/applications/SearchitTerminal.desktop ] || [ -d /usr/share/SearchitTerminal ]
    then {
            echo "Older Version Of Searchit Terminal Is Found"
            echo "Removing Old Version Files..."
            if [ -f /usr/bin/searchit ]
            then
              sudo rm /usr/bin/searchit /usr/bin/googleit /usr/bin/duckit
            fi

            if [ -f /usr/share/applications/SearchitTerminal.desktop ]
            then
              sudo rm /usr/share/applications/SearchitTerminal.desktop
            fi

            if [ -d /usr/share/SearchitTerminal ]
            then
              sudo rm -r /usr/share/SearchitTerminal
            fi

            if [ -d /usr/share/icons/SearchitTerminal ]
            then
              sudo rm -r /usr/share/icons/SearchitTerminal
            fi

            if [ -d ~/.searchit ]
            then
              sudo rm -r ~/.searchit
            fi

            if [ -f /usr/share/applications/st.desktop ]
            then
              sudo rm /usr/share/applications/st.desktop ]
            fi
            echo "Old Version Of Searchit Terminal Removed"
          }
        else {
          echo " No Older Version Of Searchit Terminal Is Found"
        }
fi
echo "Installing Newer Version Of Searchit Terminal"
