Document: searchit-terminal
Title: Debian searchit-terminal Manual
Author: <insert document author here>
Abstract: This manual describes what searchit-terminal is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/searchit-terminal/searchit-terminal.sgml.gz

Format: postscript
Files: /usr/share/doc/searchit-terminal/searchit-terminal.ps.gz

Format: text
Files: /usr/share/doc/searchit-terminal/searchit-terminal.text.gz

Format: HTML
Index: /usr/share/doc/searchit-terminal/html/index.html
Files: /usr/share/doc/searchit-terminal/html/*.html
